defaults:
  - dataset: deterministic_all
  - _self_

random_seed: 42

hydra:
  job:
    config:
      override_dirname:
        exclude_keys: ["random_seed"]
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}-${hydra.job.config_name}+${hydra.job.override_dirname}
